# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile
    - run: yarn test

    - name: Send mail
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: The "${{ github.job }}" job in ${{ github.repository }} repository has failed
        content_type: text/html
        body: |
          <html>
            <body>
              <h2>${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has failed.</h2>
              <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">First Link</a>
              <a href="${{ job.url }}">Second Link</a>
              
            </body>
          </html>
        # comma-separated string, send email to
        to: alex@dream-coding.com
        # from email name
        from: GitHub Robot
    
