# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile
    - run: yarn test

    - name: Send mail
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: The "${{ github.job }}" job in ${{ github.repository }} repository has failed
        content_type: text/html
        body: |
          <html>
            <body>
              <h2>${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has failed.</h2>
              <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" target="_blank" style="background-color: #28a745 !important; box-sizing: border-box; color: #fff; text-decoration: none; position: relative; display: inline-block; font-size: inherit; font-weight: 500; line-height: 1.5; white-space: nowrap; vertical-align: middle; cursor: pointer; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; border-radius: .5em; -webkit-appearance: none; -moz-appearance: none; appearance: none; box-shadow: 0 1px 0 rgba(27,31,35,.1),inset 0 1px 0 hsla(0,0%,100%,.03); transition: background-color .2s cubic-bezier(.3,0,.5,1); font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji !important; padding: .75em 1.5em; border: 1px solid #28a745;">View workflow run</a>
            </body>
          </html>
        # comma-separated string, send email to
        to: alex@dream-coding.com
        # from email name
        from: GitHub Robot
    
